// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-OybysRvG3jL_WgABAv2Cq7PdeHVFm0',
    appId: '1:256790942517:web:b966358a214f5dc927327c',
    messagingSenderId: '256790942517',
    projectId: 'dealtheka-5bfdf',
    authDomain: 'dealtheka-5bfdf.firebaseapp.com',
    storageBucket: 'dealtheka-5bfdf.firebasestorage.app',
    measurementId: 'G-YSF3YHXHJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDewJ3MdqjWMlwzeQ5akxkFuezfOGWBF9Y',
    appId: '1:256790942517:android:f3d1681d1cdeb45d27327c',
    messagingSenderId: '256790942517',
    projectId: 'dealtheka-5bfdf',
    storageBucket: 'dealtheka-5bfdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9mS_eXm9o3IdmTBcEoUOphRHeOlY9kE',
    appId: '1:256790942517:ios:361d2da8ce829a2327327c',
    messagingSenderId: '256790942517',
    projectId: 'dealtheka-5bfdf',
    storageBucket: 'dealtheka-5bfdf.firebasestorage.app',
    iosBundleId: 'com.example.dealtheka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE9mS_eXm9o3IdmTBcEoUOphRHeOlY9kE',
    appId: '1:256790942517:ios:361d2da8ce829a2327327c',
    messagingSenderId: '256790942517',
    projectId: 'dealtheka-5bfdf',
    storageBucket: 'dealtheka-5bfdf.firebasestorage.app',
    iosBundleId: 'com.example.dealtheka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-OybysRvG3jL_WgABAv2Cq7PdeHVFm0',
    appId: '1:256790942517:web:cf0e82f2753a9fc927327c',
    messagingSenderId: '256790942517',
    projectId: 'dealtheka-5bfdf',
    authDomain: 'dealtheka-5bfdf.firebaseapp.com',
    storageBucket: 'dealtheka-5bfdf.firebasestorage.app',
    measurementId: 'G-T9CGFSYN0Z',
  );

}